const photos = [
  "aaron-burden-RgTI2KaQ5N4-unsplash.jpg",
  "alex-block-PdDBTrkGYLo-unsplash.jpg",
  "alex-knight-4NJoYCuWDok-unsplash.jpg",
  "alex-wong-l5Tzv1alcps-unsplash.jpg",
  "ant-rozetsky-H9m6mfeeakU-unsplash.jpg",
  "bailey-zindel-II5GT90rplw-unsplash.jpg",
  "chris-grafton-mRxHNzxeYt8-unsplash.jpg",
  "chris-lawton-3Ik7xWYJv3U-unsplash.jpg",
  "christian-joudrey-DuD5D3lWC3c-unsplash.jpg",
  "christoffer-engstrom-wc9avd2RaN0-unsplash.jpg",
  "christoph-von-gellhorn-kjA82leKmJc-unsplash.jpg",
  "clay-banks-z_DkoUqgx6M-unsplash.jpg",
  "daniel-plan-JjsDRttcSzA-unsplash.jpg",
  "david-sola-3guU1kCxxy0-unsplash.jpg",
  "denys-nevozhai-7nrsVjvALnA-unsplash.jpg",
  "ed-259-xcrI6CPkkJs-unsplash.jpg",
  "florian-schmid-yDgg69ofPO8-unsplash.jpg",
  "frank-mckenna-CSeCKeW4TM0-unsplash.jpg",
  "frank-mckenna-OD9EOzfSOh0-unsplash.jpg",
  "ganapathy-kumar-L75D18aVal8-unsplash.jpg",
  "gary-bendig-WPmPsdX2ySw-unsplash.jpg",
  "hendrik-cornelissen--qrcOR33ErA-unsplash.jpg",
  "hiroko-yoshii-9y7y26C-l4Y-unsplash.jpg",
  "ian-dooley-DuBNA1QMpPA-unsplash.jpg",
  "ilse-orsel-5cKc2ryLj4g-unsplash.jpg",
  "j-z0HvnhfuZjI-unsplash.jpg",
  "jared-verdi-PNKwdJ8WetM-unsplash.jpg",
  "jaromir-kavan-vv-oEGlN-4E-unsplash.jpg",
  "jezael-melgoza-layMbSJ3YOE-unsplash.jpg",
  "joe-mcdaniel-twm0BhBTPE0-unsplash.jpg",
  "john-fowler-aaIN3y2zcMQ-unsplash.jpg",
  "john-fowler-RsRTIofe0HE-unsplash.jpg",
  "kalen-emsley-_LuLiJc1cdo-unsplash.jpg",
  "kristopher-roller-zepnJQycr4U-unsplash.jpg",
  "leslie-cross-w-CC_weXj1M-unsplash.jpg",
  "lightscape-LtnPejWDSAY-unsplash.jpg",
  "luca-bravo-O453M2Liufs-unsplash.jpg",
  "mar-bustos-ARVFsI-32Uk-unsplash.jpg",
  "marina-YmQ0-nmWcV0-unsplash.jpg",
  "marita-kavelashvili-ugnrXk1129g-unsplash.jpg",
  "mike-enerio-yPbBYE1pkHo-unsplash.jpg",
  "nicolas-jehly-LzVB84KkZOE-unsplash.jpg",
  "photoholgic-RSSZ8XEuwpc-unsplash.jpg",
  "pietro-de-grandi-JHyncp5UTJs-unsplash.jpg",
  "ruslan-bardash-WMSvsWzhM0g-unsplash.jpg",
  "sava-bobov-nPc9sDIqyfI-unsplash.jpg",
  "sebastien-gabriel--IMlv9Jlb24-unsplash.jpg",
  "sigmund-rMW9us4NCzU-unsplash.jpg",
  "silas-baisch-ceITO2rlDgc-unsplash.jpg",
  "simon-berger-twukN12EN7c-unsplash.jpg",
  "stanley-dai-QLfjlyEamV4-unsplash.jpg",
  "tienko-dima-uYoVf9I6ANI-unsplash.jpg",
  "tina-rolf-yuF2B5Zyz88-unsplash.jpg",
  "tobias-keller-2ecH5Lw3zSk-unsplash.jpg",
  "tobias-tullius-PXXtq6bp6cs-unsplash.jpg",
  "valdemaras-d-7VPFyhB_j8Y-unsplash.jpg",
  "valdemaras-d-CJAVJ5SF6gA-unsplash.jpg",
  "will-van-wingerden-dsvJgiBJTOs-unsplash.jpg"
]


const chosenPhoto = photos[Math.floor(Math.random()*photos.length)];
const backgroundPhoto = document.createElement("img");

backgroundPhoto.src = `photo/${chosenPhoto}`;
document.body.appendChild(backgroundPhoto);

backgroundPhoto.id = 'backgroundPhoto';